sonata_admin:
    title: 'Admin Area'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    security:
         handler: sonata.admin.security.handler.role

    templates:
        dashboard: 'dashboard.html.twig'

sonata_notification:
    admin:
        enabled: false

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_user:
    security_acl: false
    manager_type: orm
    class:
        user:  App\Application\Sonata\UserBundle\Entity\User
        group: App\Application\Sonata\UserBundle\Entity\Group
    admin:
        user:
            class: App\Application\Sonata\UserBundle\Admin\UserAdmin

